version: '3'

services:

  mysql:
    image: quay.io/debezium/example-mysql:1.9
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: debezium
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw
    ports:
      - 3306:3306
    healthcheck:
      interval: 5s
      retries: 20
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]

  connect:
    image: quay.io/debezium/connect:1.9
    container_name: connect
    hostname: connect
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      BOOTSTRAP_SERVERS: kafka-1:9092,kafka-2:9093
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      GROUP_ID: 1
    ports:
      - 8083:8083
    healthcheck:
      interval: 5s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8083/connectors

networks:
  default:
    name: is-using-kop-a-good-idea
