version: '3'

services:

  schema-registry:
    image: confluentinc/cp-schema-registry:7.2.1
    container_name: schema-registry
    hostname: schema-registry
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka-1:9092,kafka-2:9093
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:7081
    ports:
      - 7081:7081
    healthcheck:
      interval: 5s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:7081

  ksqldb-server:
    image: confluentinc/ksqldb-server:0.27.2
    container_name: ksqldb-server
    hostname: ksqldb-server
    depends_on:
      schema-registry:
        condition: service_healthy
    environment:
      KSQL_BOOTSTRAP_SERVERS: kafka-1:9092,kafka-2:9093
      KSQL_HOST_NAME: ksqldb-server
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_KSQL_SCHEMA_REGISTRY_URL: http://schema-registry:7081
    ports:
      - 8088:8088
    healthcheck:
      interval: 5s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8088/info

networks:
  default:
    name: is-using-kop-a-good-idea
